[package]
name = "anubis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-lang-diagnostics = "2.3.1"
cairo-lang-filesystem = "2.3.1"
cairo-lang-parser = "2.3.1"
cairo-lang-syntax = "2.3.1"
